### ISSUE TITLE
Notice of Removal of Iamtregsthedev from the organization

### ISSUE THREAD

**Issue by sweezyio** [ScratchUtilities/gobo.cf#101]
I know this isn't the best place to put this but I wanted this to be publicly documented.

Hello @IamTregsthedev, 
I have decided to remove you from the Scratch Utilities organization. This is for several reasons that I will list below.
- 8 of your 17 commits to gobo.icu have been adding your name to the lists of contributors.
      - In fact, your first commit to this repository was adding your name to the list of contributors. (f8df01b)
- The "features" that you have worked on haven't ever been completed (#66 and #69) or weren't useful in the first place. (#88)
- All of your communication has been full of spelling and grammar mistakes. (Professionalism is very important)
~~With that being said, I will transfer your project (Frontia) back to you because it is your project.~~ I cannot transfer a repository from an organization to a user at this time. Instead, you will retain Admin privileges on that particular repository. 

Kindest Regards,
Kenneth Sweezy

**Comment by radioblahaj** [comment]
Hey there,

Please do not remove me from this project. I have been very busy with personal projects over the last couple months. 

I agree, I haven't done much here. But I'm just getting started, please give me a month, i can show my worth. 

The grammer errors, are something that I have improved on over the last couple months as well.

**Comment by radioblahaj** [comment]
> Hey there,
> 
> Please do not remove me from this project. I have been very busy with personal projects over the last couple months. 
> 
> I agree, I haven't done much here. But I'm just getting started, please give me a month, i can show my worth. 
> 
> The grammer errors, are something that I have improved on over the last couple months as well.
> 
> 


Give me a month and I'll be able to finish this.

**Comment by sweezyio** [comment]
> Hey there,
> 
> Please do not remove me from this project. I have been very busy with personal projects over the last couple months.
> 
> I agree, I haven't done much here. But I'm just getting started, please give me a month, i can show my worth.
> 
> The grammer errors, are something that I have improved on over the last couple months as well.

I stand by my decision. In the past 1.5 years, you have only made 17 commits, 8 of which were adding your name to the list of contributors. If you were so busy with personal projects, then you shouldn't have said that you were going to work on features for this project. On numerous occasions, you said that a feature would be complete within a few days, and none of them were ever complete.

I am sorry, but I will not be inviting you back to the organization.

**Comment by radioblahaj** [comment]
Dude please, I can beheld.ive been very busy over the last cohple mo yhs. Give me one more chance to me please

**Comment by radioblahaj** [comment]
If you don't its okay thanks for having me here
