### ISSUE TITLE
shorten URLs further

### ISSUE THREAD

**Issue by DeleteThisAcount** [ScratchUtilities/gobo.cf#14]
get rid of having ?to=	

convert base 10 project IDs to base 64

**Comment by RainbowLegend** [comment]
We have issue templates for a reason: it would help if you better collected your thoughts in a format easy for you or to use our templates.

**Comment by KennethSweezy** [comment]
Please use one of the [templates](https://github.com/ScratchUtilities/gobo.cf/blob/master/.github/ISSUE_TEMPLATE) when submitting an issue.
