### ISSUE TITLE
shorten urls further

### ISSUE THREAD

**Issue by DeleteThisAcount** [ScratchUtilities/gobo.cf#15]
**Is your feature request related to a problem? Please describe.**
URLS shortened with gobo.cf are too long to be called short.

**Describe the solution you'd like**
Convert base 10 project IDs into base 64 for example. And remove ?to=
Example
gobo.cf/p/MkN+L
instead of gobo.cf/p/?to=210821003

**Comment by KennethSweezy** [comment]
Would you be willing to implement this feature?

**Comment by DeleteThisAcount** [comment]
no

**Comment by KennethSweezy** [comment]
I have decided to not use this suggestion, as to make this utility easier to use. (However, I did omit "?to=" as to shorten it a bit more)
