### ISSUE TITLE
Enable GitHub Pages SSL 

### ISSUE THREAD

**Issue by kerrtrvs** [ScratchUtilities/gobo.cf#28]
You should definitely enable GitHub Pages SSL in settings. 🔒

**Comment by kerrtrvs** [comment]
Note: I didn't use the issue template as it's pretty self-explanatory.

**Comment by KennethSweezy** [comment]
Thanks for the issue! I have now enabled HTTPS through GitHub pages, as well as routed it through Cloudflare to make the site faster and more secure.
