### ISSUE TITLE
input and output are hidden by nav bar

### ISSUE THREAD

**Issue by space-elephant** [ScratchUtilities/gobo.cf#31]
When you go to the index.html of gobo.cf, the input field, convert button and output paragraph
are covered by the navigation bar.
If you open it in the inspector and delete the nav bar, it works perfectly. (except that there isn't a nav bar)
This could be fixed by adding two or three &lt;br&gt; tags after the nav bar but before the inputs.

Edit: changed code to use &amp;lt;br&amp;gt; and so show the &lt;br&gt; tag instead of interpreting it as HTML.

**Comment by KennethSweezy** [comment]
Thanks for bringing this to my attention, mind opening a PR with the changes since you seem to have a possible solution in mind.

**Comment by space-elephant** [comment]
<-1>
I can't use these acronyms, what's a PR?

**Comment by KennethSweezy** [comment]
A PR is a pull request. I was asking if you could create a fork of this repository, make the changes you specified, then make a pull request to this repo so I can merge them to the main branch.
