### ISSUE TITLE
Create Promotional Material(s)

### ISSUE THREAD

**Issue by KennethSweezy** [ScratchUtilities/gobo.cf#32]
The purpose of this issue is to request help from people who are better at design than me.

I am looking for someone to create some promotional materials for advertising Gobo.

Sizes that are definitely needed:
640x288 (For [MakerAds](https://makerads.xyz/)
250x250 (For Scratch Signatures)
125x125 (For Scratch Signatures)

Things to be included:
A picture of Gobo
"A Scratch URL Shortener" or something similar

**Comment by Andreto** [comment]
![gobo_poster](https://user-images.githubusercontent.com/28541538/50550584-86920680-0c73-11e9-8856-1051d49ab148.png)
Something like this?

**Comment by KennethSweezy** [comment]
Yes! That is perfect!

**Comment by Andreto** [comment]
@KennethSweezy When are we going to make the official release and what promotional material do we need for it?

**Comment by IamTregsthedev** [comment]
Yeah, I can get this on Prouducthunt. I'm adding it as a prouduct right now, so if you can give me your twitter ign's or make  an acc there. It's a place where makers and people Pubilsh Prouducts.

I'm making one right now btw, gonna make one soon

**Comment by KennethSweezy** [comment]
@IamTregsthedev I appreciate all of the help you have provided already, however, I would prefer that I create the ProductHunt page since I am the founder of the project.

**Comment by IamTregsthedev** [comment]
Sure. Just make sure to add all members, like me as makers.

**Comment by KennethSweezy** [comment]
@Andreto I think I am going to schedule the release for April 1st, 2019. This would allow us to do any extra changes that are needed as well as work out any bugs.

**Comment by KennethSweezy** [comment]
Also, if anyone would like to see the stats of our ad you can look [here](https://makerads.xyz/stats/ads/?id=5c2e927945d097571a8043df).

**Comment by Andreto** [comment]
@KennethSweezy Maybe we should make it April 3rd or something, April 1st is not really a trustworthy day on the internet.

**Comment by IamTregsthedev** [comment]
@Andreto  @KennethSweezy  I agree, April 3rd or April 6th would be good dates. It's best to launch a product on a Saturday (april 6th).

**Comment by KennethSweezy** [comment]
@Andreto Yea, I totally agree. I just wanted to give a rough estimate of when I would like to publish.

@IamTregsthedev Not trying to discredit what you say, but it appears that it is [best to launch during the early morning hours of Sunday](https://thenextweb.com/insider/2018/01/19/much-needed-research-shows-effectively-launch-product-product-hunt/).

Also according to [the article](https://thenextweb.com/insider/2018/01/19/much-needed-research-shows-effectively-launch-product-product-hunt/), it appears that we will need 7-9 images in order to yield the best result.

I will draft a tagline and description for the PH page.
What is everyone's PH Username?

**Comment by IamTregsthedev** [comment]
My is Tregsthedev

**Comment by Andreto** [comment]
Bb code snippet for forum signatures:
`[center][url=https://gobo.cf/][img]https://u.cubeupload.com/andreto/goboposter1200x300.png[/img][/url][/center]`

![goboforummockup](https://user-images.githubusercontent.com/28541538/53936075-f7f19980-40a8-11e9-9324-a66c65a56c72.PNG)

**Comment by KennethSweezy** [comment]
@Andreto True, I just wanted to give a rough estimate of when we should release.

@IamTregsthedev Well, from what I see [it is best to launch in the early morning on Sunday](https://thenextweb.com/insider/2018/01/19/much-needed-research-shows-effectively-launch-product-product-hunt/).

But anyways, I will draft a ProductHunt description and tagline.
