### ISSUE TITLE
Create Landing Page

### ISSUE THREAD

**Issue by KennethSweezy** [ScratchUtilities/gobo.cf#4]
I am looking for someone who is skilled in web design to create a landing page for Gobo.cf in a similar format to that of the [About](https://gobo.cf/about/) page.

**Comment by RJWadley** [comment]
Any particular content on the page? Probably the logo, the name, maybe a text box or a call to action button?

**Comment by JoyBhalla** [comment]
What all do you need?

**Comment by JoyBhalla** [comment]
What all do you need?

**Comment by KennethSweezy** [comment]
@JoyBhalla The above comment by RJWadley has everything that I want.

**Comment by photonOne** [comment]
I can probably help [once github stops being weird](status.github.com). I'm not good with making stuff from scratch but i can help tweak it i guess?

**Comment by codeKAMAT** [comment]
I will

**Comment by KennethSweezy** [comment]
It seems as if several people are working on this. If everyone who is working on this one could disclose that here that would be good.

**Comment by KennethSweezy** [comment]
@codeKAMAT @callmeanto Any progress on this issue?

**Comment by DeleteThisAcount** [comment]
i will do this

**Comment by KennethSweezy** [comment]
Thanks for completing this issue @Andreto!
