### ISSUE TITLE
Update Contributor List

### ISSUE THREAD

**Issue by KennethSweezy** [ScratchUtilities/gobo.cf#40]
Currently, only 6 of the 10 Contributors are listed on the "About" page. 

### Steps to Complete:
1. Add the other 4 contributors
2. Link to their GitHub Profiles

**Comment by KennethSweezy** [comment]
Thanks to @Andreto for completing this one!

**Comment by IamTregsthedev** [comment]
I need by Name to be on it to

**Comment by Andreto** [comment]
@IamTregsthedev Done. Just need to wait and see if the site updates. You are a front end guy right?

**Comment by IamTregsthedev** [comment]
@Andreto  Yup. I was just having a bit of trouble. I Just Woke up around that time, And I was a bit confused.

**Comment by KennethSweezy** [comment]
Site is updated, the logo is just a bit big. @Andreto

**Comment by Andreto** [comment]
Bigger than, yours and mine?

**Comment by Andreto** [comment]
Oh, I think I know why it looks so weird, I put him at the end right?

**Comment by KennethSweezy** [comment]
Looks like that could be the reason.
