### ISSUE TITLE
Project Editor Links

### ISSUE THREAD

**Issue by Andreto** [ScratchUtilities/gobo.cf#41]
Currently, the project editor Links are not supported on either ends of the converter. From scratch Url to gobo Url you just get a normal project Url (Not intentional, but works well until we fixed it.) If u enter a /p/e# Url u get forwarded to some weird scratch Url. I suggest we first get the site to correctly forward the /p/e# links and then we can implement it in the Scratch to gobo Url Converter.

**Comment by space-elephant** [comment]
I think that this was leftover from 2.0's editor form.
2.0:https://scratch.mit.edu/projects/<ID>/#editor
3.0:https://scratch.mit.edu/projects/editor/<ID>/

**Comment by Andreto** [comment]
I'm currently looking through the issue, but I wonder if we could use /e# instead of /p/e#. It would be easier to program and give shorter links.
@KennethSweezy

**Comment by KennethSweezy** [comment]
That sounds good. 👍

**Comment by Andreto** [comment]
Closed with [commit](https://github.com/ScratchUtilities/gobo.cf/commit/a31afeafdd76825500a371e2b87c091fc1faa2b7)
