### ISSUE TITLE
why is it .cf?

### ISSUE THREAD

**Issue by space-elephant** [ScratchUtilities/gobo.cf#42]
What has gobo.**cf** to do with the central African republic? Was it just the cheapest domain?

**Comment by KennethSweezy** [comment]
While .com would work, it does add an extra character to the URL, and it adds an extra character to everywhere the current "Gobo.cf" name is.

**Comment by space-elephant** [comment]
In that case, there is nothing better than gobo.cf with the same length.

**Comment by space-elephant** [comment]
go.bo also looks more like a link shortener (bit.ly, youtu.be). If you wanted to sow the relation to scratch, you could use scrat.ch, if you made it clear that is unofficial.

**Comment by KennethSweezy** [comment]
Domains of that shortness tend to be very expensive, especially go.bo, it is only two characters and is very valuable.

**Comment by space-elephant** [comment]
I see. It is also easy to confuse with gob.bo
