### ISSUE TITLE
Far Future Plans (gobodb)

### ISSUE THREAD

**Issue by KennethSweezy** [ScratchUtilities/gobo.cf#43]
I have now created a new repository under ScratchUtilities that will be the home of the gobodb project. You can see some of the ideas that I have had about gobodb [here](https://github.com/ScratchUtilities/gobo.cf/projects/4). Or, if you want to visit the new repository, it is [here](https://github.com/ScratchUtilities/gobodb).

I am not requesting any contributions for this one as this is more of a test to see if something of this nature would even be possible.

**Comment by IamTregsthedev** [comment]
Comment Bots aren't  allowed on scratch

**Comment by KennethSweezy** [comment]
Well then, we could just "manually" do it with the help of a script.

**Comment by IamTregsthedev** [comment]
I guess so.

**Comment by KennethSweezy** [comment]
Gonna close this since it seems to be inactive. If someone is doing development on this feature feel free to reopen it.
