### ISSUE TITLE
Inconsistant js indentation

### ISSUE THREAD

**Issue by space-elephant** [ScratchUtilities/gobo.cf#45]
**Describe the bug**
Some .js files have two spaces of indentation and some have four.

**To Reproduce**
1. open the /files/ folder
2. open contribUsers.js Note the 2-space indentation
3. go back and open create.js This one has four-spaces

**Expected behavior**
I think that all files should use four-space indentation.

**Can you create a fix?**
Yes, get a indentation program to fix it, or just search/replace two spaces with four spaces.

**Additional context**
None

**Comment by Andreto** [comment]
The create.js and the use.js are not in use anymore. All the js files in use are written by me in the same program and all use 2-space indent. If someone wants to make all of them 4 space then that's fine for me. Also, maybe we should delete the create.js and the use.js science their not in use.

**Comment by space-elephant** [comment]
Ok, how do I delete a file?

**Comment by Andreto** [comment]
The trash can icon next to the "Edit this file" button.
