### ISSUE TITLE
Let me help

### ISSUE THREAD

**Issue by IamTregsthedev** [ScratchUtilities/gobo.cf#46]
I can help with this. I'm a Front end Devloper and Marketer

**Comment by KennethSweezy** [comment]
Sure you can help! Just find something you wish to improve, or if you would like to be directed to do something, I would prefer you to work on [gobodb](https://github.com/ScratchUtilities/gobodb).

**Comment by KennethSweezy** [comment]
Or [gobo.chrome](https://github.com/ScratchUtilities/gobo.chrome)!

**Comment by IamTregsthedev** [comment]
Can I Be invited to the org?

**Comment by KennethSweezy** [comment]
Done!
