### ISSUE TITLE
Recent update causes home page to not work

### ISSUE THREAD

**Issue by KennethSweezy** [ScratchUtilities/gobo.cf#48]
@space-elephant The recent update you made caused everything to break. Nothing works now, the redirection, the converter on the home page, none of it.

**Comment by space-elephant** [comment]
https://gobo.cf/#p827
https://gobo.cf/#e827
https://gobo.cf/#uspace_elephant
https://gobo.cf/#s74
https://gobo.cf/#d98f

Also, there should be some way to shorten posts (https:<id>//scratch.mit.edu/discuss/post/&lt;id&gt;/)

**Comment by space-elephant** [comment]
fixed.
