### ISSUE TITLE
More Performant Animation of the Landing Page

### ISSUE THREAD

**Issue by jamesbmadden** [ScratchUtilities/gobo.cf#49]
Currently, the animation of the landing page is done by running a callback every two milliseconds. The way the animations isn't very performant, especially on lower-power devices, because 1) It forces the browser to rerender and relayout the page every 2 milliseconds, and 2) it does animation work that the browser already has more efficient solutions for.

Using CSS Transitions with CSS Transforms would resolve both issues, and make animations much smoother.

Alternate solutions could be using CSS Animations, but its syntax doesn't make as much sense in this case, or Web Animations API, which doesn't have great support, but would put the animation code inside the function, as right now, which would be good.

My implementation can be seen [here](https://github.com/jamesbmadden/gobo.cf/tree/patch-1). If you agree with this feature suggestion, I'll create a pull request.

EDIT: The live code can be ran [here](https://jamesbmadden.github.io/gobo.cf/). The background image does not appear because it uses a / at the start of its URL, rather than a ./,  like all the other files.

EDIT 2: I have a draft pull request here. It's a draft, and it won't be finished until there's been discussion on this issue.

**Comment by space-elephant** [comment]
Looks good, and much better, but maybe slow it down a little?

The background image does not appear because it uses a / at the start of its URL, rather than a ./, like all the other files.
I made a mistake then: originally all the files used / and I changed it so it would work on file:///home/russell/Documents/russell/gobo.cf

**Comment by jamesbmadden** [comment]
Okay, I slowed down the animations. I'll open the pull request now.

**Comment by jamesbmadden** [comment]
I set Gobo's Position back to where it should have been.

**Comment by space-elephant** [comment]
Both are good. Merging./.

**Comment by space-elephant** [comment]
merged.
