### ISSUE TITLE
Revamp README

### ISSUE THREAD

**Issue by KennethSweezy** [ScratchUtilities/gobo.cf#5]
The README needs to be updated to make it look more appealing.

**Comment by KennethSweezy** [comment]
Things I wish to have included in the README: (For my personal reference)

- Project Logo (When we get one)
- Description from [About](https://gobo.cf/about) page.

**Comment by appy9** [comment]
#20 

I tried to revamp it a bit, please check.

**Comment by KennethSweezy** [comment]
Thanks @appy9 !
