### ISSUE TITLE
Setting Display: None Breaks the Animation

### ISSUE THREAD

**Issue by jamesbmadden** [ScratchUtilities/gobo.cf#51]
A recent commit added styles to hide the converter page with ```display: none``` until the button is pressed. The issue is that the browser (tested in the latest versions of desktop Firefox, Chrome, and Safari) no longer animates the entrance. I'm assuming it's because it doesn't have a frame to animate from, so it just appears. Removing the ```display: none``` style fixes the issue. 

**To Reproduce**
1. Go to the homepage ([gobo.cf](https://gobo.cf))
2. Click on 'Shorten URL'

**Expected behavior**
After the start page slides out, the converter page slides in.

**Actual Behavior**
The converter page instantly appears in place, as the start page slides out.

**Can you create a fix?**
Remove ```display: none``` from the ```#fillinPage``` style in ```files/styles.css```.

**Additional context**
The change that caused this bug is meant to fix an issue, so my fix may make that issue come back. I do not know what the issue was, so I can't test my suggested fix for that issue.

**Comment by Andreto** [comment]
I now used "visibility: hidden;" instead. This should fix the issue.

**Comment by KennethSweezy** [comment]
Has this issue been resolved? If so please close the issue.

**Comment by jamesbmadden** [comment]
Sorry, yes, I'll close it now
