### ISSUE TITLE
Help Out with Translation

### ISSUE THREAD

**Issue by KennethSweezy** [ScratchUtilities/gobo.cf#53]
We are currently looking for several multilingual individuals who would be willing to help us out by translating Gobo.cf

Current Languages we would like to translate into:
- Spanish
- French
- Chinese

If you have any suggestions of other languages for the project translated into please suggest them here.

Languages Currently Translated:
- French (Thanks @locness3 )
- Swedish (Thanks @Andreto )
- German (Thanks @M-S-72 & @Smilingouido )

**Comment by locness3** [comment]
Would love to contribute for French!

**Comment by KennethSweezy** [comment]
@locness3 Alright, can you send me your email address so I can invite you to the Transifex project?

**Comment by locness3** [comment]
Can't you add me with my Transifex username (locness3) ?

**Comment by KennethSweezy** [comment]
Sorry, didn't know you already had an account!

I have invited you to the Transifex project.

**Comment by KennethSweezy** [comment]
@locness3 Thank you for the French Translations! Do you know anyone else who could possibly help out with the translations? (Including Languages currently not listed)

**Comment by locness3** [comment]
> @locness3 Thank you for the French Translations! Do you know anyone else who could possibly help out with the translations? (Including Languages currently not listed)

Nope

**Comment by locness3** [comment]
Please use my suggestion for the homepage text, since I figured that the original takes too much space with the line break

**Comment by locness3** [comment]
Please use my translations suggestions, strings you submitted aren't correct.

**Comment by KennethSweezy** [comment]
Ok, I apologize. Which ones need fixing?

**Comment by locness3** [comment]
You should check all

**Comment by Andreto** [comment]
@KennethSweezy I could translate it to Swedish/Svenska if u want.

**Comment by KennethSweezy** [comment]
Alright, ill set up Swedish on Transifex.

**Comment by Andreto** [comment]
@KennethSweezy how do I access the Transifex Project?

**Comment by KennethSweezy** [comment]
It will be much easier if you make an account and then tell me your
username. This will allow me to invite you directly to the project.

**Comment by Andreto** [comment]
I made a Transifex account with the username **Andreto**.

**Comment by KennethSweezy** [comment]
@Andreto 
I invited you to the Transifex project.

**Comment by M-S-72** [comment]
I can translate to German.

**Comment by Andreto** [comment]
@M-S-72 We are using [Transifex](https://www.transifex.com) for translations. If you already have a Transifex account you can just send your username and we will add you. If u don't, the best thing would be if you make one and then send the username.

**Comment by M-S-72** [comment]
@Andreto My Transifex username is M_S_72.

**Comment by Andreto** [comment]
@M-S-72 I'm not able to add people to the project but I will pass on the information to @KennethSweezy and he will add you as soon as he is online.

**Comment by KennethSweezy** [comment]
@M-S-72 I just invited you to the project. 

@Andreto Did you receive the invite to the project?

**Comment by Andreto** [comment]
@KennethSweezy Yes I did, and I finished the Swedish translation.

**Comment by KennethSweezy** [comment]
@Andreto Thank you for the translation. I have made your translations live and they should be appearing on the site soon!

**Comment by KennethSweezy** [comment]
@Andreto Could you add @M-S-72 to the contributor list on the About page since they are translating into German?

**Comment by Andreto** [comment]
@KennethSweezy I'm adding **M. S.** and **locness**.

**Comment by locness3** [comment]
@KennethSweezy Please accept my suggestion for the homepage "Url shortener for Scratch projects...", as it actually takes too much space on screen.
Also, please accept my suggestion for the "Enter URL"

**Comment by Andreto** [comment]
@locness3 I don't really think that it matters if the text takes a bit more space then on the English version. The information is more important in that case. And we have space to take from, at least on normal sized screens.

**Comment by locness3** [comment]
Ok. But the Enter URL current translation isn't correct.

**Comment by KennethSweezy** [comment]
@locness3 Transifex isn't showing me your updated translation. Could you just tell me what it needs to be here? I will manually override the current one.

**Comment by locness3** [comment]
"Entrer une URL"

**Comment by KennethSweezy** [comment]
@locness3 Alright, it has been updated.

@Andreto Can you translate: "Preview links I click on" into Swedish, it is showing that it hasn't been translated.

**Comment by locness3** [comment]
But, you do use a Transifex paid plan ? @KennethSweezy

**Comment by KennethSweezy** [comment]
@locness3 Technically yes, I am using the plan provided by the [GitHub Education Pack](https://education.github.com/pack/offers).

**Comment by Andreto** [comment]
@KennethSweezy Fixed, it was not there when I translated the rest.

**Comment by locness3** [comment]
> @locness3 Technically yes, I am using the plan provided by the [GitHub Education Pack](https://education.github.com/pack/offers).

Argh, I need to wait to be 13 just to make a Transifex live project....

**Comment by locness3** [comment]
Just saw this was only one year of Transifex included in student pack. What will you do when it will expire @KennethSweezy ?

**Comment by Andreto** [comment]
A bigger issue, what do we do when the gobo.cf domain expires? Or have you paid for it @KennethSweezy ?

**Comment by locness3** [comment]
@Andreto Doing a whois, the domain name is apparently registered on www.dot.cf, which seems to be partnered with freenom, and offers free .cf domains

**Comment by locness3** [comment]
@Andreto Just type gobo.cf on https://whois.net/

**Comment by Andreto** [comment]
Free Freenom domains only last one year. When the domain expires it gets a new price (often not free) calculated by the website's traffic during the free year. So if gobo.cf is successful witch I hope it gets, the domain will be more expensive to keep.

**Comment by locness3** [comment]
@KennethSweezy

**Comment by KennethSweezy** [comment]
@locness3 Hopefully Transifex will continue to be a partner with GitHub Education Pack and I can continue to use it for free.

@Andreto Currently, I am only using a free .cf domain, but I am looking at purchasing a similar domain name from a proper registrar.

**Comment by locness3** [comment]
> @locness3 Hopefully Transifex will continue to be a partner with GitHub Education Pack and I can continue to use it for free.

I mean they will still be partners, and the offer will still exist, but it is limited to one year.

**Comment by space-elephant** [comment]
> @locness3 Hopefully Transifex will continue to be a partner with GitHub Education Pack and I can continue to use it for free.
> 
> @Andreto Currently, I am only using a free .cf domain, but I am looking at purchasing a similar domain name from a proper registrar.

*Technically* possible as free, with g.py.gl. (same length as gobo.cf)
It probably makes more sense to buy a proper domain name. (possibly with de)

**Comment by space-elephant** [comment]
> @locness3 Hopefully Transifex will continue to be a partner with GitHub Education Pack and I can continue to use it for free.
> 
> @Andreto Currently, I am only using a free .cf domain, but I am looking at purchasing a similar domain name from a proper registrar.

*Technically* possible as free, with g.py.gl. (same length as gobo.cf)
It probably makes more sense to buy a proper domain name. (possibly with de)

**Comment by space-elephant** [comment]
@KennethSweezy I am on transifex as rfmorland@gmail.com

**Comment by space-elephant** [comment]
@KennethSweezy I am on transifex as space_elephant(rfmorland@gmail.com)

**Comment by space-elephant** [comment]
@KennethSweezy I am on transifex as space_elephant(rfmorland@gmail.com)

**Comment by space-elephant** [comment]
Can I add a JavaScript file to use google translate in the case that there is nothing better?

**Comment by space-elephant** [comment]
> Can I add a JavaScript file to use google translate in the case that there is nothing better?

What are the 1 and 1 about?

**Comment by KennethSweezy** [comment]
Google Translate is notoriously bad with accurate translations. Trust me, at one point I thought about including Google Translate but then did some research and it turns out it isn't good for accurately translating entire webpages.

**Comment by KennethSweezy** [comment]
@space-elephant What language would you like to translate the site into? I need to specify a language before I invite you.

**Comment by space-elephant** [comment]
> Google Translate is notoriously bad with accurate translations. Trust me, at one point I thought about including Google Translate but then did some research and it turns out it isn't good for accurately translating entire webpages.

I mean for languages not in range of live.js, Writing a script for this purpose (does not enter images of iframes)

**Comment by Smilingouido** [comment]
I can help with german!

**Comment by KennethSweezy** [comment]
@Smilingouido Alright! What is your Transifex username?

**Comment by Smilingouido** [comment]
I don't have this.

**Comment by locness3** [comment]
> I don't have this.

Transifex is the localization platform that uses gobo.cf

**Comment by KennethSweezy** [comment]
@Smilingouido Don't worry, you can create an account for free, once you have done this just send your Username.

**Comment by KennethSweezy** [comment]
@locness3 There is currently an untranslated string: "Preview links I click on"

Do you mind translating this to French?

**Comment by Smilingouido** [comment]
> @Smilingouido Don't worry, you can create an account for free, once you have done this just send your Username.

Okay, I'll do.

**Comment by Smilingouido** [comment]
My username is: Smilingouido

**Comment by KennethSweezy** [comment]
@Smilingouido Alright, I have accepted your join request.

**Comment by Smilingouido** [comment]
Okay, thank you.

**Comment by M-S-72** [comment]
In 478b231, "Shorted Url" was changed to "Shortened Url", but on Transifex it is still "Shorted Url".

**Comment by KennethSweezy** [comment]
I will update that right away.

**Comment by rdgutierrez** [comment]
I can help with spanish

**Comment by KennethSweezy** [comment]
Ok! First, what is your Transifex username? (If you don't have an account
with Transifex, an email address is fine) Second, what dialect of Spanish
do you want me to select? (The options are: Argentinian Spanish, Latin
American Spanish, Mexican Spanish, European Spanish (Spain), or United
States Spanish)

**Comment by saarahasad** [comment]
I can translate to Arabic and Hindi. Is that needed

**Comment by KennethSweezy** [comment]
Yes! That would be great! What is your Transifex username?

**Comment by KennethSweezy** [comment]
@rdgutierrez @saarahasad All I need is your Transifex username or an email address and I will get you set up for translation.

**Comment by KennethSweezy** [comment]
@rdgutierrez @saarahasad Are you still wishing to contribute to this project?

**Comment by KennethSweezy** [comment]
I am going to create a new issue for translations.
