### ISSUE TITLE
Placement of Maker Ad(s)

### ISSUE THREAD

**Issue by KennethSweezy** [ScratchUtilities/gobo.cf#54]
Currently, we have an ad on [MakerAds](https://makerads.xyz/) created for #32.

I feel that since we have an ad on MakerAds we should include a MakerAd somewhere on the Gobo.cf site.

Where should we place it? Or should we have one at all?

**Comment by IamTregsthedev** [comment]
We should have one for sure. It should be in the footer

`<footer>
insert makersads
</footer>`

**Comment by KennethSweezy** [comment]
@Andreto @IamTregsthedev So, currently I think the best options are either between the one-liner and the "Contributors" header. Or, beneath all of the contributors.

I would like to finish this up before release.

**Comment by Andreto** [comment]
Maybe Just in the top corner for the about page.
![Skärmklipp](https://user-images.githubusercontent.com/28541538/55638499-9e73ac00-57c7-11e9-9792-feae5e82fbd4.PNG)
Are we going to have an ad on the main page too?

**Comment by KennethSweezy** [comment]
I say the corner on the About page is good. No ad on the home page.

**Comment by Andreto** [comment]
Ok, il make a commit.

**Comment by Andreto** [comment]
[makerAd on about-page](https://github.com/ScratchUtilities/gobo.cf/commit/04ad06fe968d6fb6718da757821f0034334300e8)

**Comment by KennethSweezy** [comment]
@Andreto Looks good!
