### ISSUE TITLE
Faster redirects

### ISSUE THREAD

**Issue by space-elephant** [ScratchUtilities/gobo.cf#55]
**Is your feature request related to a problem? Please describe.**
Redirect links always load all the stylesheets before redirecting

**Describe the solution you'd like**
I would like to replace the `#` with a `/`, and then use a 404.html for redirects. Invalid ones would show the default 404.

**Describe alternatives you've considered**
The homepage could be at homepage.html and the javascript at index.html could redirect to homepage.html when given an empty hash.

**Additional context**
Null

**Comment by Andreto** [comment]
I think that we should move the homepage to a different folder and have the main index.html blank from elements and styling. That way we don't lock up the 404 pages and we can keep the same code as before. We can have blank and invalid hashes redirect to the home page.

**Comment by space-elephant** [comment]
> I think that we should move the homepage to a different folder and have the main index.html blank from elements and styling. That way we don't lock up the 404 pages and we can keep the same code as before. We can have blank and invalid hashes redirect to the home page.

OK. Should I put the new homepage at
/homepage.html or /homepage or /homepage/index.html (/homepage/)

**Comment by Andreto** [comment]
I think we should make it `/home/index.html`, the URL looks best that way.
