### ISSUE TITLE
Launch Preperation

### ISSUE THREAD

**Issue by KennethSweezy** [ScratchUtilities/gobo.cf#56]
# TARGET PUBLISH DATE IS APRIL 7TH, 2019

This issue is for everything related to the Launch of Gobo.cf on ProductHunt and any other platforms we wish to publish it on. (All comments relating to PH from #32 please move your discussion to this issue.)

**Publishing Platforms:**
- ProductHunt
- Scratch Forums
- Suggest others.

**Comment by IamTregsthedev** [comment]
Social media.

I'll do it on my twitter, and we can make a twitter which all team members can acces

**Comment by Andreto** [comment]
My ProductHunt username is @andreto

**Comment by KennethSweezy** [comment]
@IamTregsthedev Sounds good!

@Andreto I will be sure to add you when I create the post.

@keithieopia 
@ncomendant 
@space-elephant 
@chexbox 
@jamesbmadden 
@appy9 
@Avantika-Didroy 
@RainbowLegend 
Please send me your Product Hunt Username so I can tag you as makers on the Product Page!

**Comment by IamTregsthedev** [comment]
You should only put Members of the Org. But, It's alright :)!

I'll get Started making an acc for ScratchUtlites.

I have something called prixy. It show's the scratch front page, Can I transfer it here? It would still be owned by me and my startup Moo. But it's a Scratch utillte

**Comment by KennethSweezy** [comment]
Yeah, go ahead and transfer it.

**Comment by IamTregsthedev** [comment]
Can you give everyone push access to it, expect me?

**Comment by IamTregsthedev** [comment]
Actully nvm. I wouldn't be able to control the settings of the repo, so there's no reason to do so

**Comment by space-elephant** [comment]
> @IamTregsthedev Sounds good!
> 
> @Andreto I will be sure to add you when I create the post.
> 
> @keithieopia
> @ncomendant
> @space-elephant
> @chexbox
> @jamesbmadden
> @appy9
> @Avantika-Didroy
> @RainbowLegend
> Please send me your Product Hunt Username so I can tag you as makers on the Product Page!

I will sign up if you tell me what ProductHunt.Com is meant to be. (It doesn't work  for me.)

**Comment by space-elephant** [comment]
> @IamTregsthedev Sounds good!
> 
> @Andreto I will be sure to add you when I create the post.
> 
> @keithieopia
> @ncomendant
> @space-elephant
> @chexbox
> @jamesbmadden
> @appy9
> @Avantika-Didroy
> @RainbowLegend
> Please send me your Product Hunt Username so I can tag you as makers on the Product Page!

I will sign up if you tell me what ProductHunt.Com is meant to be. (It doesn't work  for me.)

**Comment by IamTregsthedev** [comment]
> > @IamTregsthedev Sounds good!
> > @Andreto I will be sure to add you when I create the post.
> > @keithieopia
> > @ncomendant
> > @space-elephant
> > @chexbox
> > @jamesbmadden
> > @appy9
> > @Avantika-Didroy
> > @RainbowLegend
> > Please send me your Product Hunt Username so I can tag you as makers on the Product Page!
> 
> I will sign up if you tell me what ProductHunt.Com is meant to be. (It doesn't work for me.)

It's a website where people launch products such as robots and web apps.

**Comment by space-elephant** [comment]
> > > @IamTregsthedev Sounds good!
> > > @Andreto I will be sure to add you when I create the post.
> > > @keithieopia
> > > @ncomendant
> > > @space-elephant
> > > @chexbox
> > > @jamesbmadden
> > > @appy9
> > > @Avantika-Didroy
> > > @RainbowLegend
> > > Please send me your Product Hunt Username so I can tag you as makers on the Product Page!
> > 
> > 
> > I will sign up if you tell me what ProductHunt.Com is meant to be. (It doesn't work for me.)
> 
> It's a website where people launch products such as robots and web apps.

@space_elephant

**Comment by IamTregsthedev** [comment]
Hey @KennethSweezy, T-minus 6 days till launch! Any plans?

**Comment by KennethSweezy** [comment]
Finishing up on the release notes for all of the platforms we are
advertising on. (ProductHunt, Scratch Forums, etc)

**Comment by keithieopia** [comment]
> @IamTregsthedev Sounds good!
> 
> @Andreto I will be sure to add you when I create the post.
> 
> @keithieopia
> @ncomendant
> @space-elephant
> @chexbox
> @jamesbmadden
> @appy9
> @Avantika-Didroy
> @RainbowLegend
> Please send me your Product Hunt Username so I can tag you as makers on the Product Page!

[@keithieopia](https://www.producthunt.com/@keithieopia)

**Comment by IamTregsthedev** [comment]
Can we Launch April 5th?

**Comment by KennethSweezy** [comment]
Is there any reason why the 5th is better than the 7th?

**Comment by IamTregsthedev** [comment]
Not really. A friday would be much better to Launch a product in my Book. The best time to launch at 12am SF(Product Hunt Time).

**Comment by Andreto** [comment]
@KennethSweezy Do you have all the assets that you need for the launch or do you need any additional graphics or promotional materials.

**Comment by KennethSweezy** [comment]
I do need some graphics as well as screenshots. The graphics I would like
one of them to be an image with the basic description of what gobo.cf is.

**Comment by IamTregsthedev** [comment]
I can take screenshots. I| get this done

**Comment by IamTregsthedev** [comment]
![lpmagcflph](https://user-images.githubusercontent.com/21000033/55677254-8d539980-58b2-11e9-81a6-655a498e95c6.png)
![phgoboml](https://user-images.githubusercontent.com/21000033/55677255-8dec3000-58b2-11e9-8fff-78660a3557b6.png)

**Comment by KennethSweezy** [comment]
Ok, @Andreto do you think you could very quickly make a 240x240 image that
represents Gobo? If so please do.

**Comment by IamTregsthedev** [comment]
Hey @KennethSweezy 

12 PST would be the best time to launch. @KennethSweezy  Is The screenshots fine?

**Comment by KennethSweezy** [comment]
Yes, those screenshots are good.

**Comment by IamTregsthedev** [comment]
k

**Comment by appy9** [comment]
@appy9

**Comment by Andreto** [comment]
@KennethSweezy Made this is it good? Also, have a look around in my gobo.cf design folder to see if you find something you need. https://1drv.ms/f/s!Ao2pUhGGTP094GhLE30E2njNoHt9
![goboicon](https://user-images.githubusercontent.com/28541538/55679209-e00b7080-5907-11e9-862f-e5c5dd71c058.png)

**Comment by IamTregsthedev** [comment]
you haven't launched yet?

**Comment by KennethSweezy** [comment]
Sorry about not launching, I am really sick at the moment. We will launch next week.

@Andreto That icon looks great!

**Comment by IamTregsthedev** [comment]
No Promblem. Health is more important

**Comment by KennethSweezy** [comment]
@appy9 @keithieopia @space-elephant @Andreto 
I have scheduled the release for tomorrow morning at 12:01 AM.
**[ProductHunt](https://www.producthunt.com/posts/gobo-cf)**

**Comment by IamTregsthedev** [comment]
@KennethSweezy  I not in there ...

**Comment by IamTregsthedev** [comment]
PLEASE @KennethSweezy  fix this, there is less than 10 minutes till launch

**Comment by IamTregsthedev** [comment]
I'm getting us some Upvotes

**Comment by KennethSweezy** [comment]
@IamTregsthedev What is your ProductHunt Username?

**Comment by IamTregsthedev** [comment]
Tregsthedev

**Comment by KennethSweezy** [comment]
@IamTregsthedev Ok, Updated. Sorry for the inconvenience.

**Comment by IamTregsthedev** [comment]
No promblem, Sorry for my behevior

**Comment by IamTregsthedev** [comment]
We've Lauched: https://www.producthunt.com/newest

**Comment by IamTregsthedev** [comment]
We should switch to glicth, It has Link Tracking and Customs too. Gonna transfer and see if it supports

**Comment by KennethSweezy** [comment]
@IamTregsthedev As much as I think this would be a good idea, we should wait before we test it. You know, since we literally launched like 10 mins ago....

**Comment by KennethSweezy** [comment]
I archived this to keep it as the history of the launch.

**Comment by IamTregsthedev** [comment]
> We should switch to glicth, It has Link Tracking and Customs too. Gonna transfer and see if it supports

Yes, Sorry. I think it would be nice to Support custom links :).

**Comment by Andreto** [comment]
@KennethSweezy Have we advertised it on the scratch forums?

**Comment by KennethSweezy** [comment]
Not yet. Feel free to write something up for it. Just let me read over it
before it is posted.

**Comment by IamTregsthedev** [comment]
:D
