### ISSUE TITLE
Put my website link in contributors

### ISSUE THREAD

**Issue by locness3** [ScratchUtilities/gobo.cf#58]
**Is your feature request related to a problem? Please describe.**
The link of my profile pic in the Contributors page points to my Github profile.

**Describe the solution you'd like**
I would like it to link to my website, `https://locness3.github.io`.

**Comment by Andreto** [comment]
Fixed [c6d76ea](https://github.com/ScratchUtilities/gobo.cf/commit/c6d76ea7adf619a3cb29399f3ed6c15c73ff1733)

**Comment by locness3** [comment]
@Andreto  You could the inverse (putting Fixes #58 in commit message)
