### ISSUE TITLE
Set standard for how we write paths.

### ISSUE THREAD

**Issue by Andreto** [ScratchUtilities/gobo.cf#59]
At most places in the project the HTML path's start with `../` to refer to the file. Is there any special reason for this, because if it isn't I would recommend that we start using just `/`. This way we refer to it with full path and we can have the same path regardless of where in the filesystem we are using it. @space-elephant

**Comment by space-elephant** [comment]
I personally like fully relative paths because they will work in https://space-elephant.github.io/gobo.cf/ and file:///home/russell/Documents/russell/gobo.cf

**Comment by Andreto** [comment]
Ok. I use Atom and live-server-package to test the site. That way it behaves just like on the real page.
