### ISSUE TITLE
No scroll bars

### ISSUE THREAD

**Issue by space-elephant** [ScratchUtilities/gobo.cf#60]
**Describe the bug*

**To Reproduce**
1. Go to https://gobo.cf/home/ (http://gobo.cf)
2. Look at bottom of screen
4. See shorten URL and preview links I click on overlaping
4. Look at the right of screen
5. see no scroll bar

**Expected behavior**
The page should appear the same, with the nav bar fixed to the top, and the "Preview links click on" fixed on bottom, but with a scroll bar at side

**Screenshots**
NOT NEEDED

**Can you create a fix?**
No, I am no good at CSS.

**Additional context**
What is this section for again?

**Comment by Andreto** [comment]
I will take a look at it, I get back to you.

**Comment by Andreto** [comment]
I have now added a media query that changes up the layout a bit for smaller screens.
[#75280d7](https://github.com/ScratchUtilities/gobo.cf/commit/75280d78ccaa11a19aaac9d5a1cdfa58ecaa3a88)
