### ISSUE TITLE
page for license/privacy notice

### ISSUE THREAD

**Issue by chexbox** [ScratchUtilities/gobo.cf#61]
I think it would be beneficial to have a page for the license and privacy notice. I started a branch for a page. I based it off the 'about' page, but it still needs a lot of work.

I started by adding the license title and a link. I also mentioned that we don't actually own Gobo (that should be fairly obvious to users of scratch).

Any thoughts or suggestions?

**Comment by space-elephant** [comment]
https://gobo.cf/LICENSE
