### ISSUE TITLE
Swap Placement of Gobo and Scratchcat

### ISSUE THREAD

**Issue by KennethSweezy** [ScratchUtilities/gobo.cf#62]
Currently, above the shorten URL button, it shows the following:
![Screenshot 2019-03-26 at 9 09 43 PM](https://user-images.githubusercontent.com/33377824/55043235-af742e80-500b-11e9-8caf-867f3febd1cb.png)
However, I believe that it would be better if the Scratchcat was first and then Gobo was second. This would show that you are converting Scratch URL's into Gobo URL's.

What are your thoughts on this?

**Comment by Andreto** [comment]
I thought of this when I made it but I didn't bother to change the SVG file before testing it. I also think it makes more sense the other way around on this page so I will fix it.

**Comment by Andreto** [comment]
[155eb56](https://github.com/ScratchUtilities/gobo.cf/commit/155eb561bf9f0754049801af94b333a550eb8883)
