### ISSUE TITLE
„Preview links I click on“ in German is not completely shown on my mobile

### ISSUE THREAD

**Issue by M-S-72** [ScratchUtilities/gobo.cf#64]
**Describe the bug**
When I use Gobo.cf on my iPhone in German, the „Preview links I click on“ („Link-Vorschau anzeigen“) box is not completely visible.

**To Reproduce**
1. Go to gobo.cf on a mobile
2. Use German

**Expected behavior**
You can see the „Preview links I click on“ („Link-Vorschau anzeigen“) box correctly.

**Screenshots**
![166AEE3C-B9CA-4852-ABA6-756CC489515F](https://user-images.githubusercontent.com/46165762/56213676-cb904c00-605c-11e9-96a9-076ac70da5c3.jpeg)
The text on the box in the bottom right is not completely shown.

**Can you create a fix?**
Maybe.

**Comment by Andreto** [comment]
The rot of this is a bigger problem, so I will close this and move the discussion to #65.
