### ISSUE TITLE
Mobile Compatibility

### ISSUE THREAD

**Issue by Andreto** [ScratchUtilities/gobo.cf#65]
This issue is for discussions and progress on **making a gobo.cf mobile compatible**. This has been a long time coming, but I got reminded of it with #64. I will self asign myself and start working on it in the near future.

**Comment by Andreto** [comment]
https://github.com/ScratchUtilities/gobo.cf/commit/203401a6cece8e36da5e0d716c3da4e4536c860e
Started working on it.

**Comment by Andreto** [comment]
https://github.com/ScratchUtilities/gobo.cf/commit/8f2d197a4232666ecb6b4feb23fc67f145288a7c

**Comment by KennethSweezy** [comment]
@Andreto I apologize for not responding to this sooner. But in the Cloudflare configurations, I can set the site to automatically redirect to a specific subdomain if a person is accessing the site from mobile. The only issue is having to basically have a separate repository for the mobile site that is almost exactly the same.

**Comment by Andreto** [comment]
I think how it is now works pretty good and detects most phones. To have one more repo to update would make as lot of extra work. Also I was finished with this feature I just forgot to close this issue, so if we're not going to use cloudflare I will close this.

**Comment by KennethSweezy** [comment]
Since you already have a solution in place I think I will close it.

Thank you for your continued dedication to this project.
