### ISSUE TITLE
Fixing Darkmode

### ISSUE THREAD

**Issue by IamTregsthedev** [ScratchUtilities/gobo.cf#69]
@IamTregsthedev I agree it looks pretty bad. Especially things like Gobo, inputs (like @Andreto mentioned), and the GitHub Link in the top corner.

_Originally posted by @KennethSweezy in https://github.com/ScratchUtilities/gobo.cf/pull/66#issuecomment-506982632_

----

Yes I know, I'm fix this when I'm free, Don't have good wifi at the moment on vaction

**Comment by chexbox** [comment]
Using css variables might work for custom colors. I know @infinitytec has used them in the past for themes.

**Comment by KennethSweezy** [comment]
@IamTregsthedev Have you made any progress on this issue?

**Comment by IamTregsthedev** [comment]
No, Sorry I've been Busy with school. 

I try this week

**Comment by KennethSweezy** [comment]
I am going to close this issue since it is stale.

**Comment by IamTregsthedev** [comment]
I'm sorry, I've been really busy, and I promise for sure a slove by the next 2 weeks,
