### ISSUE TITLE
Remove <center> elements

### ISSUE THREAD

**Issue by RJWadley** [ScratchUtilities/gobo.cf#7]
The <center> element is obsolete. Although it may still work in some browsers, its use is discouraged since it could be removed at any time.

It should be replaced project-wide.

**Comment by Thilagavathi1** [comment]
@RJWadley , Shall i pick this issue?.

**Comment by KennethSweezy** [comment]
@Thilagavathi1 You can take this one if you would like.

**Comment by jokari** [comment]
Fixed in #8

**Comment by KennethSweezy** [comment]
Did you add additional styling to keep the elements centered?

**Comment by jokari** [comment]
@KennethSweezy done in another commit ;)

**Comment by KennethSweezy** [comment]
Thanks for the contribution!
