### ISSUE TITLE
Help Out with Translation

### ISSUE THREAD

**Issue by KennethSweezy** [ScratchUtilities/gobo.cf#71]
Currently, we are trying to allow this project to be used by more and more people. To do that we need translators! 

If you would like to help translate Gobo.cf into other languages follow the bellow checklist:
- Be fluent in English and at least one other language.
- Have a Transifex account (create an account [here](http://transifex.com/signup))

Languages that have been translated into:
- French (@locness3)
- Swedish (@Andreto)
- German (@M-S-72 & @Smilingouido)
- Persian (@FarzanHosseini)
- Spanish (@jsedano)
- Portuguese (Brazil) (@brunopulis)
- Russian (@yanicka)
- Ukrainian (@yanicka)
- Hindi (@imbdb)
- Lithuanian (@mantasio)
- Dutch (@pjgeutjens)

If you would like to help translate just leave a comment here with your Transifex username and what language you would like to translate it into.

If you know a language that has already been translated, please still review the project to ensure correctness.

**Comment by KennethSweezy** [comment]
@ScratchUtilities/translators Please go back to the Transifex project and make sure that all translations are correct and up to date.

**Comment by jsedano** [comment]
Hey I would like to help with Spanish
Transifex user: jsedano

**Comment by Andreto** [comment]
Updated Swedish(sv)

**Comment by KennethSweezy** [comment]
@jsedano Okay! I have added you to the Transifex project. I tried to translate the project myself with my very limited knowledge of the Spanish language. Make any changes that you need.

**Comment by FarzanHosseini** [comment]
Hey I can help on Persian(Farsi) language 
Transfix Username: Farzan

**Comment by KennethSweezy** [comment]
@FarzanHosseini Okay! I have added you to the Transifex project.

**Comment by jsedano** [comment]
Hey @KennethSweezy I just finished with the Strings in Spanish, should I mark them as reviewed and open a PR or something ?

**Comment by KennethSweezy** [comment]
You can just mark them as reviewed in Transifex if they look correct.

**Comment by brunopulis** [comment]
Hey I would like to help with Brazilian Portuguese
Transifex user: brunopulis

**Comment by KennethSweezy** [comment]
@brunopulis Okay! I have added the ability to translate into Brazilian Portuguese and invited you to the project. Good luck with your translations!

**Comment by yanicka** [comment]
I would like to translate it into Russian and/or Ukrainian. My username is yanicka

**Comment by KennethSweezy** [comment]
@yanicka Thank you for your willingness to contribute! I have invited you to the Transifex project so that you can translate the project into Russian and Ukrainian.

**Comment by KennethSweezy** [comment]
@all-contributors please add @locness3 for translation
@all-contributors please add @Andreto for translation
@all-contributors please add @M-S-72 for translation
@all-contributors please add @Smilingouido for translation
@all-contributors please add @FarzanHosseini for translation
@all-contributors please add @jsedano for translation
@all-contributors please add @brunopulis for translation

**Comment by KennethSweezy** [comment]
@all-contributors please add @locness3 for translation

**Comment by KennethSweezy** [comment]
@all-contributors please add @Andreto for translation

**Comment by KennethSweezy** [comment]
@all-contributors please add @M-S-72, @Smilingouido, @FarzanHosseini, @jsedano, @brunopulis for translation

**Comment by KennethSweezy** [comment]
@all-contributors please add @M-S-72 @Smilingouido @FarzanHosseini @jsedano @brunopulis for translation

**Comment by KennethSweezy** [comment]
@all-contributors please add @Smilingouido for translation

**Comment by KennethSweezy** [comment]
@all-contributors please add @FarzanHosseini for translation

**Comment by KennethSweezy** [comment]
@all-contributors please add @jsedano for translation

**Comment by KennethSweezy** [comment]
@all-contributors please add @brunopulis for translation

**Comment by imbdb** [comment]
Language: Hindi
Transifex username: imbdb

**Comment by KennethSweezy** [comment]
@imbdb Okay! I have added you to the project for translation to Hindi. Thank you in advance.

**Comment by KennethSweezy** [comment]
@locness3 Could you update the translations for French?

@M-S-72 @Smilingouido Can you update the translations for German?

**Comment by mantasio** [comment]
Hey, I can help with Lithuanian translations. Transifex username: mantasio

**Comment by ChingChang9** [comment]
I would love to help to translate this to Traditional Chinese if you guys need it.

**Comment by KennethSweezy** [comment]
@mantasio Okay! You have been added to the project. Good luck.

**Comment by locness3** [comment]
Yes!

**Comment by locness3** [comment]
Please use my suggestion for "shorten URL ->"

**Comment by KennethSweezy** [comment]
@locness3 Thanks for the updates. I have now used your suggestions for all strings.

**Comment by Smilingouido** [comment]
@KennethSweezy I'll do that in the next days.

**Comment by KennethSweezy** [comment]
@Smilingouido Ok, thank you.

**Comment by Smilingouido** [comment]
No Problem...

Samuel Bittrich

Am 06.10.2019 um 18:28 schrieb Kenneth Blake Sweezy <notifications@github.com<mailto:notifications@github.com>>:


@Smilingouido<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSmilingouido&data=02%7C01%7C%7C86f62c46452e4b098f8d08d74a7a2acf%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637059760864400594&sdata=GrBzlFq7qdjBOJ%2BfE64bYeD6wimiBIAuq5%2BZMjKLSE4%3D&reserved=0> Ok, thank you.

**Comment by Smilingouido** [comment]
@KennethSweezy No problem.

**Comment by pjgeutjens** [comment]
I could help out with Dutch translation
transifex username: pjgeutjens

**Comment by KennethSweezy** [comment]
@pjgeutjens Okay! I have added you to the project! Good luck!

**Comment by AdityaFRC** [comment]
I cam help out with German, Hindi, and Marathi translation.
transifex username: AdiPat

**Comment by Ph1lbert** [comment]
username: Ph1lbert 
lang : greek

**Comment by Seihla** [comment]
Hi, I can help a bit with translating into Khmer (Cambodian)
Username: IsaiahSeihla

**Comment by NotRealPaz** [comment]
username: NotRealPaz
Thai Translation

**Comment by KennethSweezy** [comment]
@AdityaFRC @Ph1lbert @Seihla @NotRealPaz I have added all of you to the languages that you requested. 

Good luck with your translations!

**Comment by NotRealPaz** [comment]
@KennethSweezy I want to preview my translation but can't due to this issue #84

**Comment by munex-com** [comment]
Hi, I could help out with Japanese translation.
Transifex username: munex_com

**Comment by cracknutmeg** [comment]
Transifex username : cracknut
Language : Hindi

**Comment by KennethSweezy** [comment]
@munex-com @cracknutmeg I have added both of you to the languages that you have requested.

**Comment by Smollet777** [comment]
There is a typo on about page in russian. There is "Gobo.cf - это сократите**с**ь". Should be "Gobo.cf - это сократите**л**ь".

**Comment by haidarrifki** [comment]
hey, I want to help with Indonesian (bahasa)
Transifex username: haidarrifki

**Comment by KennethSweezy** [comment]
@haidarrifki I have added you to the Transifex project. 

@Smollet777 I have made the correction.

**Comment by backciro** [comment]
Hello I think that I could help for the Italian (it-IT) translation.
My transifex id is: @mntmtt 

Regards :)

**Comment by teegr** [comment]
Hi , I can work on Armenian translation 

transifex id : teegrik

**Comment by yecicen** [comment]
Hi, I can translate to Turkish. 
Transifex user: yecicen

**Comment by rakeshlanjewarwork** [comment]
Hi , I can work on Marathi (India) translation

transifex id : rakeshlanjewar

**Comment by R4356th** [comment]
I can translate to Bengali. I have a Transifex account and I am also a Scratch Translator.

**Comment by R4356th** [comment]
Transifex id: R4356th

**Comment by R4356th** [comment]
@KennethSweezy , is translating plan put down?

**Comment by KennethSweezy** [comment]
Since the project has been unable to be usable for a while. I am going to close this issue for now. 

Thank You to all of the contributors and prospective contributors.
